apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: movie-booking
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
      - name: nuclear-clean
        image: busybox
        command: ['sh', '-c', 'rm -rf /var/lib/mysql/* && ls -la /var/lib/mysql']
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      containers:
      - name: mysql
        image: mysql:8.0.42  # Pinned version
        command: 
        - sh
        - -c
        - |
          if [ ! -f /var/lib/mysql/mysql ]; then
            mysqld --initialize-insecure
          fi
          exec mysqld
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc