# mysql-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: movie-booking
spec:
  accessModes:
   storageClassName: minikube-sc
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: mysql-pv
  storageClassName: ""  # Must match PV