name: Microservices CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_REGISTRY: docker.io
  K8S_NAMESPACE: microservices
  APP_VERSION: ${{ github.sha }}

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest  # Only if you need pytest
        
    - name: Verify installation
      run: |
        pip show Flask mysqlclient requests python-dotenv || exit 1
        echo "✓ All dependencies installed"

    - name: Test imports
      run: |
        python -c "
        try:
            import flask
            from microservices.services import bookings, movies, showtimes, user
            from microservices.database import db_connection
            print('✓ All modules import successfully')
        except ImportError as e:
            print(f'✗ Import failed: {str(e)}')
            exit(1)
        "

  build-and-push:
    needs: setup-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [booking-service, movie-service, showtime-service, user-service]
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    - name: Build and push
      run: |
        docker build \
          -t ${{ env.DOCKER_REGISTRY }}/22i1140/${{ matrix.service }}:${{ env.APP_VERSION }} \
          -t ${{ env.DOCKER_REGISTRY }}/22i1140/${{ matrix.service }}:latest \
          --build-arg SERVICE_MODULE=${{ matrix.service }} \
          .
        docker push ${{ env.DOCKER_REGISTRY }}/22i1140/${{ matrix.service }}:${{ env.APP_VERSION }}
        docker push ${{ env.DOCKER_REGISTRY }}/22i1140/${{ matrix.service }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/setup-kubectl@v3
    
    - name: Configure Kubernetes
      run: |
        # Decode and save kubeconfig
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
        chmod 600 kubeconfig.yaml
        
        # Verify config format
        if ! kubectl config view --kubeconfig=kubeconfig.yaml >/dev/null; then
          echo "::error::Invalid kubeconfig format"
          cat kubeconfig.yaml
          exit 1
        fi
        
        export KUBECONFIG=kubeconfig.yaml
        
        # Verify cluster connection
        if ! kubectl cluster-info >/dev/null 2>&1; then
          echo "::error::Failed to connect to cluster"
          echo "Current context:"
          kubectl config current-context
          echo "Trying to use first available context..."
          kubectl config use-context $(kubectl config get-contexts -o name | head -1)
          
          if ! kubectl cluster-info; then
            exit 1
          fi
        fi

    - name: Deploy Resources
      run: |
        # Create namespace
        kubectl create namespace ${{ env.K8S_NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
        
        # Apply configurations with retries
        for attempt in {1..3}; do
          echo "Attempt $attempt to apply configurations"
          kubectl apply --validate=false -f k8s_specification/configmaps/ -n ${{ env.K8S_NAMESPACE }} && break
          sleep 5
        done
        
        # Apply other resources similarly
        kubectl apply --validate=false -f k8s_specification/secrets/ -n ${{ env.K8S_NAMESPACE }}
        kubectl apply --validate=false -f k8s_specification/persistentvolume/ -n ${{ env.K8S_NAMESPACE }}
        
        # Update deployments
        for service in booking-service movie-service showtime-service user-service; do
          kubectl set image deployment/$service \
            $service=${{ env.DOCKER_REGISTRY }}/22i1140/$service:${{ env.APP_VERSION }} \
            -n ${{ env.K8S_NAMESPACE }} || echo "Continuing despite update failure"
        done
        
        # Apply remaining resources
        kubectl apply --validate=false -f k8s_specification/services/ -n ${{ env.K8S_NAMESPACE }}
        kubectl apply --validate=false -f k8s_specification/ingress/ -n ${{ env.K8S_NAMESPACE }}
        
        # Verify deployments with timeout
        for service in booking-service movie-service showtime-service user-service; do
          if kubectl get deployment/$service -n ${{ env.K8S_NAMESPACE }} >/dev/null 2>&1; then
            kubectl rollout status deployment/$service \
              -n ${{ env.K8S_NAMESPACE }} \
              --timeout=300s || echo "Rollout verification failed but continuing"
          fi
        done
        
        echo "✓ Deployment completed"